version: "3"

services:
  backend:
    build: ./web-backend/
    ports:
      - 5000:5000
    #para ficar rodando o docker compose
    tty: true
    depends_on:
      - db
    links:
      - db
    restart: on-failure:5
    command: >
      sh -c "npm i && npm start"
    networks:
      - frontend
      - backend

  frontend:
    build: ./web-frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    restart: on-failure:5
    depends_on:
      - backend
    command: > #sh, para invocar o shell padrao, caso use no windows, e -c para conseguir rodar um comando
      sh -c "npm i && npm start"

    networks:
      - frontend

  db:
    build: ./web-backend/src/sql
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge

volumes:
  db:
    driver: local